GPUS=${GPUS:-8}

# RAW domain
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/base/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/base/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/base/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/base/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/base/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/base/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/base/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_evaluator.outfile_prefix=work_dirs/urpc2020/base/tood_r50_fpn_1x_urpc/tood_result

# physical free methods
# HE domain   <Histogram Equalization>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py                 work_dirs/ruod/he/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py         work_dirs/ruod/he/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py          work_dirs/ruod/he/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py   work_dirs/ruod/he/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py            work_dirs/ruod/he/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                     work_dirs/ruod/he/ssd300_120e_ruod/epoch_24.pth                      $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py                 work_dirs/ruod/he/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS   --cfg-options  test_dataloader.dataset.data_prefix.img='HE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/he/tood_r50_fpn_1x_urpc/tood_result

# CLAHE domain   <Contrast Limited Adaptive Histogram Equalization>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/clahe/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/clahe/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/clahe/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/clahe/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/clahe/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/clahe/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/clahe/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CLAHE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/tood_r50_fpn_1x_urpc/tood_result

# WB domain  <White Balance>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/wb/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/wb/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/wb/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/wb/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/wb/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/wb/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/wb/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options   test_dataloader.dataset.data_prefix.img='WB/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/wb/tood_r50_fpn_1x_urpc/tood_result

# ACDC domain  <Underwater Image Enhancement by Attenuated Color Channel Correction and Detail Preserved Contrast Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/acdc/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/acdc/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/acdc/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/acdc/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/acdc/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/acdc/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/acdc/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ACDC/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/tood_r50_fpn_1x_urpc/tood_result

# physical based methods
# UDCP domain  <Underwater depth estimation and image restoration based on single images>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/udcp/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/udcp/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/udcp/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/udcp/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/udcp/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/udcp/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/udcp/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UDCP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/tood_r50_fpn_1x_urpc/tood_result

# ULAP domain  <A rapid scene depth estimation model based on underwater light attenuation prior for underwater image restoration>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/ulap/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/ulap/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/ulap/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/ulap/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/ulap/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/ulap/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/ulap/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='ULAP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/tood_r50_fpn_1x_urpc/tood_result

# DMIL_HDP domain  <Underwater image restoration based on minimum information loss principle and optical properties of underwater imaging>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/dmil_hdp/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/dmil_hdp/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/dmil_hdp/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/dmil_hdp/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/dmil_hdp/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/dmil_hdp/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/dmil_hdp/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DMIL_HDP/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/tood_r50_fpn_1x_urpc/tood_result

# GAN based methods
# TOPAL domain  <Target Oriented Perceptual Adversarial Fusion Network for Underwater Image Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/topal/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/topal/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/topal/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/topal/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/topal/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/topal/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/topal/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TOPAL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/topal/tood_r50_fpn_1x_urpc/tood_result

# TUDA domain  <Domain Adaptation for Underwater Image Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/tuda/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/tuda/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/tuda/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/tuda/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/tuda/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/tuda/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/tuda/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TUDA/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/tood_r50_fpn_1x_urpc/tood_result

# TACL domain  <Twin Adversarial Contrastive Learning for Underwater Image Enhancement and Beyond>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/tacl/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/tacl/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/tacl/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/tacl/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/tacl/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/tacl/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/tacl/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='TACL/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/tood_r50_fpn_1x_urpc/tood_result


# CNN based methods
# UIEC^2-Net domain  <UIEC^2-Net: CNN-based underwater image enhancement using two color space>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/uiec2net/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/uiec2net/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/uiec2net/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/uiec2net/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/uiec2net/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/uiec2net/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/uiec2net/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UIEC2Net/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/tood_r50_fpn_1x_urpc/tood_result

# UWCNN domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/uwcnn/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/uwcnn/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/uwcnn/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/uwcnn/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/uwcnn/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/uwcnn/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/uwcnn/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UWCNN/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/tood_r50_fpn_1x_urpc/tood_result

# DUIENet domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/duienet/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/duienet/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/duienet/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/duienet/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/duienet/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/duienet/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/duienet/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='DUIENet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/tood_r50_fpn_1x_urpc/tood_result

# CHE_GLNet domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/che_glnet/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/che_glnet/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/che_glnet/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/che_glnet/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/che_glnet/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/che_glnet/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/che_glnet/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='CHE_GLNet/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/tood_r50_fpn_1x_urpc/tood_result

# SGUIE_Net domain   <SGUIE-Net: Semantic Attention Guided Underwater Image Enhancement With Multi-Scale Perception>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/sguie/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/sguie/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/sguie/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/sguie/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/sguie/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/sguie/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/sguie/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='SGUIE/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/tood_r50_fpn_1x_urpc/tood_result

# UColor domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_test.sh configs/detection/ruod_dataset/atss_r50_fpn_1x_ruod.py               work_dirs/ruod/ucolor/atss_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/atss_r50_fpn_1x_urpc/atss_result
./tools/dist_test.sh configs/detection/ruod_dataset/cascade-rcnn_r50_fpn_1x_ruod.py       work_dirs/ruod/ucolor/cascade-rcnn_r50_fpn_1x_ruod/epoch_12.pth          $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/cascade-rcnn_r50_fpn_1x_urpc/cascade_result
./tools/dist_test.sh configs/detection/ruod_dataset/faster-rcnn_r50_fpn_1x_ruod.py        work_dirs/ruod/ucolor/faster-rcnn_r50_fpn_1x_ruod/epoch_12.pth           $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/faster-rcnn_r50_fpn_1x_urpc/faster_result
./tools/dist_test.sh configs/detection/ruod_dataset/fcos_r50-caffe_fpn_gn-head_1x_ruod.py work_dirs/ruod/ucolor/fcos_r50-caffe_fpn_gn-head_1x_ruod/epoch_12.pth    $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/fcos_r50-caffe_fpn_gn-head_1x_urpc/fcos_result
./tools/dist_test.sh configs/detection/ruod_dataset/retinanet_r50_fpn_1x_ruod.py          work_dirs/ruod/ucolor/retinanet_r50_fpn_1x_ruod/epoch_12.pth             $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/retinanet_r50_fpn_1x_urpc/retinanet_result
./tools/dist_test.sh configs/detection/ruod_dataset/ssd300_120e_ruod.py                   work_dirs/ruod/ucolor/ssd300_120e_ruod/epoch_24.pth                      $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/ssd300_120e_urpc/ssd300_result
./tools/dist_test.sh configs/detection/ruod_dataset/tood_r50_fpn_1x_ruod.py               work_dirs/ruod/ucolor/tood_r50_fpn_1x_ruod/epoch_12.pth                  $GPUS  --cfg-options  test_dataloader.dataset.data_prefix.img='UColor/test'  test_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/tood_r50_fpn_1x_urpc/tood_result
