GPUS=${GPUS:-8}

## RAW domain
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/base/atss_r50_fpn_1x_urpc                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py           $GPUS  --work-dir work_dirs/urpc2020/base/cascade-rcnn_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py            $GPUS  --work-dir work_dirs/urpc2020/base/faster-rcnn_r50_fpn_1x_urpc                 --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py     $GPUS  --work-dir work_dirs/urpc2020/base/fcos_r50-caffe_fpn_gn-head_1x_urpc          --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py              $GPUS  --work-dir work_dirs/urpc2020/base/retinanet_r50_fpn_1x_urpc                   --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                       $GPUS  --work-dir work_dirs/urpc2020/base/ssd300_120e_urpc                            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/base/tood_r50_fpn_1x_urpc                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/tood_r50_fpn_1x_urpc/eval_result
# More experiments with different backbone on Faster R-CNN.
# Note: 2x (24 epochs) may overfit
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_2x_urpc-coco.py            $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_r50_fpn_1x_urpc          --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_r50_fpn_2x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r101_fpn_1x_urpc-coco.py           $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_r101_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_r101_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r101_fpn_2x_urpc-coco.py           $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_r101_fpn_2x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_r101_fpn_2x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_x101-32x4d_fpn_1x_urpc-coco.py     $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_x101-32x4d_fpn_1x        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_x101-32x4d_fpn_1x/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_x101-32x4d_fpn_2x_urpc-coco.py     $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_x101-32x4d_fpn_2x        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_x101-32x4d_fpn_2x/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_x101-64x4d_fpn_1x_urpc-coco.py     $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_64x4d_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_64x4d_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_x101-64x4d_fpn_2x_urpc-coco.py     $GPUS  --work-dir work_dirs/urpc2020/base/faster/faster-rcnn_64x4d_fpn_2x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   val_evaluator.outfile_prefix=work_dirs/urpc2020/base/faster/faster-rcnn_64x4d_fpn_2x_urpc/eval_result

# physical free methods
# HE domain   <Histogram Equalization>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/he/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/he/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/he/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/he/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/he/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/he/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/he/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='HE'  val_dataloader.dataset.data_prefix.img='HE'  test_dataloader.dataset.data_prefix.img='HE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/he/tood_r50_fpn_1x_urpc/eval_result

# CLAHE domain   <Contrast Limited Adaptive Histogram Equalization>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/clahe/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/clahe/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/clahe/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/clahe/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/clahe/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/clahe/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/clahe/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CLAHE'  val_dataloader.dataset.data_prefix.img='CLAHE'  test_dataloader.dataset.data_prefix.img='CLAHE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/clahe/tood_r50_fpn_1x_urpc/eval_result

# WB domain  <White Balance>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/wb/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/wb/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/wb/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/wb/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/wb/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/wb/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/wb/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WB'  val_dataloader.dataset.data_prefix.img='WB'  test_dataloader.dataset.data_prefix.img='WB'  val_evaluator.outfile_prefix=work_dirs/urpc2020/wb/tood_r50_fpn_1x_urpc/eval_result

# ACDC domain  <Underwater Image Enhancement by Attenuated Color Channel Correction and Detail Preserved Contrast Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/acdc/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/acdc/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/acdc/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/acdc/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/acdc/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/acdc/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/acdc/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ACDC'  val_dataloader.dataset.data_prefix.img='ACDC'  test_dataloader.dataset.data_prefix.img='ACDC'  val_evaluator.outfile_prefix=work_dirs/urpc2020/acdc/tood_r50_fpn_1x_urpc/eval_result

# physical based methods
# UDCP domain  <Underwater depth estimation and image restoration based on single images>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/udcp/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/udcp/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/udcp/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/udcp/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/udcp/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/udcp/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/udcp/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UDCP'  val_dataloader.dataset.data_prefix.img='UDCP'  test_dataloader.dataset.data_prefix.img='UDCP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/udcp/tood_r50_fpn_1x_urpc/eval_result

# ULAP domain  <A rapid scene depth estimation model based on underwater light attenuation prior for underwater image restoration>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ulap/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/ulap/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/ulap/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/ulap/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/ulap/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/ulap/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ulap/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='ULAP'  val_dataloader.dataset.data_prefix.img='ULAP'  test_dataloader.dataset.data_prefix.img='ULAP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ulap/tood_r50_fpn_1x_urpc/eval_result

# DMIL_HDP domain  <Underwater image restoration based on minimum information loss principle and optical properties of underwater imaging>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/dmil_hdp/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_dataloader.dataset.data_prefix.img='DMIL_HDP'  test_dataloader.dataset.data_prefix.img='DMIL_HDP'  val_evaluator.outfile_prefix=work_dirs/urpc2020/dmil_hdp/tood_r50_fpn_1x_urpc/eval_result

# GAN based methods
# WaterGAN domain  <WaterGAN: Unsupervised Generative Network to Enable Real-time Color Correction of Monocular Underwater Images.>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/watergan/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/watergan/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/watergan/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/watergan/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/watergan/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/watergan/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/watergan/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='WaterGAN'  val_dataloader.dataset.data_prefix.img='WaterGAN'  test_dataloader.dataset.data_prefix.img='WaterGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/watergan/tood_r50_fpn_1x_urpc/eval_result

# UGAN domain  <Enhancing Underwater Imagery using Generative Adversarial Networks>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ugan/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/ugan/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/ugan/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/ugan/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/ugan/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/ugan/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ugan/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UGAN'  val_dataloader.dataset.data_prefix.img='UGAN'  test_dataloader.dataset.data_prefix.img='UGAN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ugan/tood_r50_fpn_1x_urpc/eval_result


# TOPAL domain  <Target Oriented Perceptual Adversarial Fusion Network for Underwater Image Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/topal/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/topal/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/topal/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/topal/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/topal/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/topal/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/topal/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TOPAL'  val_dataloader.dataset.data_prefix.img='TOPAL'  test_dataloader.dataset.data_prefix.img='TOPAL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/topal/tood_r50_fpn_1x_urpc/eval_result

# TUDA domain  <Domain Adaptation for Underwater Image Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/tuda/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/tuda/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/tuda/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/tuda/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/tuda/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/tuda/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/tuda/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TUDA'  val_dataloader.dataset.data_prefix.img='TUDA'  test_dataloader.dataset.data_prefix.img='TUDA'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tuda/tood_r50_fpn_1x_urpc/eval_result

# TACL domain  <Twin Adversarial Contrastive Learning for Underwater Image Enhancement and Beyond>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/tacl/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/tacl/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/tacl/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/tacl/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/tacl/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/tacl/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/tacl/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='TACL'  val_dataloader.dataset.data_prefix.img='TACL'  test_dataloader.dataset.data_prefix.img='TACL'  val_evaluator.outfile_prefix=work_dirs/urpc2020/tacl/tood_r50_fpn_1x_urpc/eval_result


# CNN based methods
# UIEC^2-Net domain  <UIEC^2-Net: CNN-based underwater image enhancement using two color space>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/uiec2net/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/uiec2net/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/uiec2net/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/uiec2net/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/uiec2net/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/uiec2net/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/uiec2net/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UIEC2Net'  val_dataloader.dataset.data_prefix.img='UIEC2Net'  test_dataloader.dataset.data_prefix.img='UIEC2Net'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uiec2net/tood_r50_fpn_1x_urpc/eval_result

# UWCNN domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/uwcnn/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/uwcnn/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/uwcnn/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/uwcnn/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/uwcnn/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/uwcnn/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/uwcnn/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UWCNN'  val_dataloader.dataset.data_prefix.img='UWCNN'  test_dataloader.dataset.data_prefix.img='UWCNN'  val_evaluator.outfile_prefix=work_dirs/urpc2020/uwcnn/tood_r50_fpn_1x_urpc/eval_result

# DUIENet domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/duienet/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/duienet/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/duienet/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/duienet/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/duienet/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/duienet/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/duienet/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='DUIENet'  val_dataloader.dataset.data_prefix.img='DUIENet'  test_dataloader.dataset.data_prefix.img='DUIENet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/duienet/tood_r50_fpn_1x_urpc/eval_result

# CHE_GLNet domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/che_glnet/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/che_glnet/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/che_glnet/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/che_glnet/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/che_glnet/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/che_glnet/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/che_glnet/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_dataloader.dataset.data_prefix.img='CHE_GLNet'  test_dataloader.dataset.data_prefix.img='CHE_GLNet'  val_evaluator.outfile_prefix=work_dirs/urpc2020/che_glnet/tood_r50_fpn_1x_urpc/eval_result

# SGUIE_Net domain   <SGUIE-Net: Semantic Attention Guided Underwater Image Enhancement With Multi-Scale Perception>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/sguie/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/sguie/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/sguie/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/sguie/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/sguie/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/sguie/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/sguie/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='SGUIE'  val_dataloader.dataset.data_prefix.img='SGUIE'  test_dataloader.dataset.data_prefix.img='SGUIE'  val_evaluator.outfile_prefix=work_dirs/urpc2020/sguie/tood_r50_fpn_1x_urpc/eval_result

# UColor domain  <Underwater Scene Prior Inspired Deep Underwater Image and Video Enhancement>
./tools/dist_train.sh configs/detection/duo_dataset/atss_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ucolor/atss_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/atss_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_urpc-coco.py       $GPUS  --work-dir work_dirs/urpc2020/ucolor/cascade-rcnn_r50_fpn_1x_urpc        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/cascade-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_urpc-coco.py        $GPUS  --work-dir work_dirs/urpc2020/ucolor/faster-rcnn_r50_fpn_1x_urpc         --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/faster-rcnn_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py $GPUS  --work-dir work_dirs/urpc2020/ucolor/fcos_r50-caffe_fpn_gn-head_1x_urpc  --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/fcos_r50-caffe_fpn_gn-head_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/retinanet_r50_fpn_1x_urpc-coco.py          $GPUS  --work-dir work_dirs/urpc2020/ucolor/retinanet_r50_fpn_1x_urpc           --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/retinanet_r50_fpn_1x_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/ssd300_120e_urpc-coco.py                   $GPUS  --work-dir work_dirs/urpc2020/ucolor/ssd300_120e_urpc                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0   train_dataloader.dataset.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/ssd300_120e_urpc/eval_result
./tools/dist_train.sh configs/detection/duo_dataset/tood_r50_fpn_1x_urpc-coco.py               $GPUS  --work-dir work_dirs/urpc2020/ucolor/tood_r50_fpn_1x_urpc                --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0           train_dataloader.dataset.data_prefix.img='UColor'  val_dataloader.dataset.data_prefix.img='UColor'  test_dataloader.dataset.data_prefix.img='UColor'  val_evaluator.outfile_prefix=work_dirs/urpc2020/ucolor/tood_r50_fpn_1x_urpc/eval_result
