PARTITION=$1
GPUS=${GPUS:-8}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
CPUS_PER_TASK=${CPUS_PER_TASK:-5}
SRUN_ARGS=${SRUN_ARGS:-""}

log_dir="work_dirs/slurm_logs"
mkdir -p "$log_dir"

SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-atss_r50_1x             configs/detection/urpc2020_dataset/train-all_test-A/atss_r50_fpn_1x_urpc-coco.py                   work_dirs/urpc2020-train-all/atss_r50_fpn_1x_urpc-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/atss_r50_fpn_1x_urpc-coco/eval_result                 > "$log_dir/urpc2020-train-all_atss_r50_fpn_1x_urpc-coco.log"                     &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-cascade_r50_1x          configs/detection/urpc2020_dataset/train-all_test-A/cascade-rcnn_r50_fpn_1x_urpc-coco.py           work_dirs/urpc2020-train-all/cascade-rcnn_r50_fpn_1x_urpc-coco            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/cascade-rcnn_r50_fpn_1x_urpc-coco/eval_result         > "$log_dir/urpc2020-train-all_cascade-rcnn_r50_fpn_1x_urpc-coco.log"             &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-faster_r50_1x           configs/detection/urpc2020_dataset/train-all_test-A/faster-rcnn_r50_fpn_1x_urpc-coco.py            work_dirs/urpc2020-train-all/faster-rcnn_r50_fpn_1x_urpc-coco             --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/faster-rcnn_r50_fpn_1x_urpc-coco/eval_result          > "$log_dir/urpc2020-train-all_faster-rcnn_r50_fpn_1x_urpc-coco.log"              &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-faster_r101_1x          configs/detection/urpc2020_dataset/train-all_test-A/faster-rcnn_r101_fpn_1x_urpc-coco.py           work_dirs/urpc2020-train-all/faster-rcnn_r101_fpn_1x_urpc-coco            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/faster-rcnn_r101_fpn_1x_urpc-coco/eval_result         > "$log_dir/urpc2020-train-all_faster-rcnn_r101_fpn_1x_urpc-coco.log"             &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-faster_x101-32x4d_1x    configs/detection/urpc2020_dataset/train-all_test-A/faster-rcnn_x101-32x4d_fpn_1x_urpc-coco.py     work_dirs/urpc2020-train-all/faster-rcnn_x101-32x4d_fpn_1x_urpc-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/faster-rcnn_x101-32x4d_fpn_1x_urpc-coco/eval_result   > "$log_dir/urpc2020-train-all_faster-rcnn_x101-32x4d_fpn_1x_urpc-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-faster_x101-64x4d_1x    configs/detection/urpc2020_dataset/train-all_test-A/faster-rcnn_x101-64x4d_fpn_1x_urpc-coco.py     work_dirs/urpc2020-train-all/faster-rcnn_x101-64x4d_fpn_1x_urpc-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/faster-rcnn_x101-64x4d_fpn_1x_urpc-coco/eval_result   > "$log_dir/urpc2020-train-all_faster-rcnn_x101-64x4d_fpn_1x_urpc-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-fcos_r50_1x             configs/detection/urpc2020_dataset/train-all_test-A/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.py     work_dirs/urpc2020-train-all/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/fcos_r50-caffe_fpn_gn-head_1x_urpc-coco/eval_result   > "$log_dir/urpc2020-train-all_fcos_r50-caffe_fpn_gn-head_1x_urpc-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-paa_r50_1x              configs/detection/urpc2020_dataset/train-all_test-A/paa_r50_fpn_1x_urpc-coco.py                    work_dirs/urpc2020-train-all/paa_r50_fpn_1x_urpc-coco                     --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/paa_r50_fpn_1x_urpc-coco/eval_result                  > "$log_dir/urpc2020-train-all_paa_r50_fpn_1x_urpc-coco.log"                      &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-retinanet_r50_1x        configs/detection/urpc2020_dataset/train-all_test-A/retinanet_r50_fpn_1x_urpc-coco.py              work_dirs/urpc2020-train-all/retinanet_r50_fpn_1x_urpc-coco               --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/retinanet_r50_fpn_1x_urpc-coco/eval_result            > "$log_dir/urpc2020-train-all_retinanet_r50_fpn_1x_urpc-coco.log"                &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-ssd300                  configs/detection/urpc2020_dataset/train-all_test-A/ssd300_120e_urpc-coco.py                       work_dirs/urpc2020-train-all/ssd300_120e_urpc-coco                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/ssd300_120e_urpc-coco/eval_result                     > "$log_dir/urpc2020-train-all_ssd300_120e_urpc-coco.log"                         &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-ssd512                  configs/detection/urpc2020_dataset/train-all_test-A/ssd512_120e_urpc-coco.py                       work_dirs/urpc2020-train-all/ssd512_120e_urpc-coco                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/ssd512_120e_urpc-coco/eval_result                     > "$log_dir/urpc2020-train-all_ssd512_120e_urpc-coco.log"                         &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  urpc2020-tood_r50_1x             configs/detection/urpc2020_dataset/train-all_test-A/tood_r50_fpn_1x_urpc-coco.py                   work_dirs/urpc2020-train-all/tood_r50_fpn_1x_urpc-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/urpc2020-train-all/tood_r50_fpn_1x_urpc-coco/eval_result                 > "$log_dir/urpc2020-train-all_tood_r50_fpn_1x_urpc-coco.log"                     &
