PARTITION=$1
GPUS=${GPUS:-8}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
CPUS_PER_TASK=${CPUS_PER_TASK:-5}
SRUN_ARGS=${SRUN_ARGS:-""}

log_dir="work_dirs/slurm_logs"
mkdir -p "$log_dir"

SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-atss_r50_1x             configs/detection/rtts_dataset/atss_r50_fpn_1x_rtts-coco.py                   work_dirs/rtts/atss_r50_fpn_1x_rtts-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/atss_r50_fpn_1x_rtts-coco/eval_result                 > "$log_dir/rtts_atss_r50_fpn_1x_rtts-coco.log"                     &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-cascade_r50_1x          configs/detection/rtts_dataset/cascade-rcnn_r50_fpn_1x_rtts-coco.py           work_dirs/rtts/cascade-rcnn_r50_fpn_1x_rtts-coco            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/cascade-rcnn_r50_fpn_1x_rtts-coco/eval_result         > "$log_dir/rtts_cascade-rcnn_r50_fpn_1x_rtts-coco.log"             &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-faster_r50_1x           configs/detection/rtts_dataset/faster-rcnn_r50_fpn_1x_rtts-coco.py            work_dirs/rtts/faster-rcnn_r50_fpn_1x_rtts-coco             --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/faster-rcnn_r50_fpn_1x_rtts-coco/eval_result          > "$log_dir/rtts_faster-rcnn_r50_fpn_1x_rtts-coco.log"              &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-fcos_r50_1x             configs/detection/rtts_dataset/fcos_r50-caffe_fpn_gn-head_1x_rtts-coco.py     work_dirs/rtts/fcos_r50-caffe_fpn_gn-head_1x_rtts-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/fcos_r50-caffe_fpn_gn-head_1x_rtts-coco/eval_result   > "$log_dir/rtts_fcos_r50-caffe_fpn_gn-head_1x_rtts-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-paa_r50_1x              configs/detection/rtts_dataset/paa_r50_fpn_1x_rtts-coco.py                    work_dirs/rtts/paa_r50_fpn_1x_rtts-coco                     --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/paa_r50_fpn_1x_rtts-coco/eval_result                  > "$log_dir/rtts_paa_r50_fpn_1x_rtts-coco.log"                      &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-retinanet_r50_1x        configs/detection/rtts_dataset/retinanet_r50_fpn_1x_rtts-coco.py              work_dirs/rtts/retinanet_r50_fpn_1x_rtts-coco               --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/retinanet_r50_fpn_1x_rtts-coco/eval_result            > "$log_dir/rtts_retinanet_r50_fpn_1x_rtts-coco.log"                &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  rtts-tood_r50_1x             configs/detection/rtts_dataset/tood_r50_fpn_1x_rtts-coco.py                   work_dirs/rtts/tood_r50_fpn_1x_rtts-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/rtts/tood_r50_fpn_1x_rtts-coco/eval_result                 > "$log_dir/rtts_tood_r50_fpn_1x_rtts-coco.log"                     &
