PARTITION=$1
GPUS=${GPUS:-8}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
CPUS_PER_TASK=${CPUS_PER_TASK:-5}
SRUN_ARGS=${SRUN_ARGS:-""}

log_dir="work_dirs/slurm_logs"
mkdir -p "$log_dir"

SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-atss_r50_1x             configs/detection/duo_dataset/atss_r50_fpn_1x_duo-coco.py                   work_dirs/duo/atss_r50_fpn_1x_duo-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/atss_r50_fpn_1x_duo-coco/eval_result                 > "$log_dir/duo_atss_r50_fpn_1x_duo-coco.log"                     &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-cascade_r50_1x          configs/detection/duo_dataset/cascade-rcnn_r50_fpn_1x_duo-coco.py           work_dirs/duo/cascade-rcnn_r50_fpn_1x_duo-coco            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/cascade-rcnn_r50_fpn_1x_duo-coco/eval_result         > "$log_dir/duo_cascade-rcnn_r50_fpn_1x_duo-coco.log"             &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-faster_r50_1x           configs/detection/duo_dataset/faster-rcnn_r50_fpn_1x_duo-coco.py            work_dirs/duo/faster-rcnn_r50_fpn_1x_duo-coco             --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/faster-rcnn_r50_fpn_1x_duo-coco/eval_result          > "$log_dir/duo_faster-rcnn_r50_fpn_1x_duo-coco.log"              &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-faster_r101_1x          configs/detection/duo_dataset/faster-rcnn_r101_fpn_1x_duo-coco.py           work_dirs/duo/faster-rcnn_r101_fpn_1x_duo-coco            --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/faster-rcnn_r101_fpn_1x_duo-coco/eval_result         > "$log_dir/duo_faster-rcnn_r101_fpn_1x_duo-coco.log"             &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-faster_x101-32x4d_1x    configs/detection/duo_dataset/faster-rcnn_x101-32x4d_fpn_1x_duo-coco.py     work_dirs/duo/faster-rcnn_x101-32x4d_fpn_1x_duo-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/faster-rcnn_x101-32x4d_fpn_1x_duo-coco/eval_result   > "$log_dir/duo_faster-rcnn_x101-32x4d_fpn_1x_duo-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-faster_x101-64x4d_1x    configs/detection/duo_dataset/faster-rcnn_x101-64x4d_fpn_1x_duo-coco.py     work_dirs/duo/faster-rcnn_x101-64x4d_fpn_1x_duo-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/faster-rcnn_x101-64x4d_fpn_1x_duo-coco/eval_result   > "$log_dir/duo_faster-rcnn_x101-64x4d_fpn_1x_duo-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-fcos_r50_1x             configs/detection/duo_dataset/fcos_r50-caffe_fpn_gn-head_1x_duo-coco.py     work_dirs/duo/fcos_r50-caffe_fpn_gn-head_1x_duo-coco      --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/fcos_r50-caffe_fpn_gn-head_1x_duo-coco/eval_result   > "$log_dir/duo_fcos_r50-caffe_fpn_gn-head_1x_duo-coco.log"       &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-paa_r50_1x              configs/detection/duo_dataset/paa_r50_fpn_1x_duo-coco.py                    work_dirs/duo/paa_r50_fpn_1x_duo-coco                     --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/paa_r50_fpn_1x_duo-coco/eval_result                  > "$log_dir/duo_paa_r50_fpn_1x_duo-coco.log"                      &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-retinanet_r50_1x        configs/detection/duo_dataset/retinanet_r50_fpn_1x_duo-coco.py              work_dirs/duo/retinanet_r50_fpn_1x_duo-coco               --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/retinanet_r50_fpn_1x_duo-coco/eval_result            > "$log_dir/duo_retinanet_r50_fpn_1x_duo-coco.log"                &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-ssd300                  configs/detection/duo_dataset/ssd300_120e_duo-coco.py                       work_dirs/duo/ssd300_120e_duo-coco                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/ssd300_120e_duo-coco/eval_result                     > "$log_dir/duo_ssd300_120e_duo-coco.log"                         &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-ssd512                  configs/detection/duo_dataset/ssd512_120e_duo-coco.py                       work_dirs/duo/ssd512_120e_duo-coco                        --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/ssd512_120e_duo-coco/eval_result                     > "$log_dir/duo_ssd512_120e_duo-coco.log"                         &
SRUN_ARGS=${SRUN_ARGS}  GPUS=$GPUS  GPUS_PER_NODE=$GPUS_PER_NODE  CPUS_PER_TASK=$CPUS_PRE_TASK  ./tools/slurm_train.sh  $PARTITION  duo-tood_r50_1x             configs/detection/duo_dataset/tood_r50_fpn_1x_duo-coco.py                   work_dirs/duo/tood_r50_fpn_1x_duo-coco                    --cfg-options default_hooks.checkpoint.max_keep_ckpts=1  randomness.seed=0  val_evaluator.outfile_prefix=work_dirs/duo/tood_r50_fpn_1x_duo-coco/eval_result                 > "$log_dir/duo_tood_r50_fpn_1x_duo-coco.log"                     &
